[package]
name = "antelope_transactions"
edition = "2021"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
substreams-antelope = "0.4"
substreams-database-change = "1.3"
substreams-entity-change = "1.3"
substreams = "0.5"
