[package]
name = "blocks"
version = "0.2.0"
authors = ["Denis <denis@pinax.network>", "Zhi"]
description = "Messari Blocks"
license = "MIT"
edition = "2021"
publish = false

[badges]
maintenance = { status = "actively-developed" }

[lib]
crate-type = ["cdylib"]

[dependencies]
substreams = "0.5"
substreams-ethereum = "0.9"
substreams-entity-change = "1.3"